apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jvm-build-suite-component-tkfvtm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jvm-build-suite-component-tkfvtm
    app.kubernetes.io/part-of: jvm-build-suite-application-ezlf
  name: jvm-build-suite-component-tkfvtm
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: jvm-build-suite-component-tkfvtm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: jvm-build-suite-component-tkfvtm
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/jvm-build-rjqq-tenant/jvm-build-suite-application-ezlf/jvm-build-suite-component-tkfvtm@sha256:b3e229efd6614cbfd7875433b611c7c3a3061445500ee05ac2a4d9420c1a7732
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
